apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/HarrisonZz/DevOps_Deploy.git
    targetRevision: main
    path: kubernetes/http_server
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .metadata.annotations
    - group: v1
      kind: Service
      jqPathExpressions:
        - .metadata.annotations

    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .metadata.annotations
    - group: v1
      kind: Service
      jqPathExpressions:
        - .metadata.annotations
