apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HarrisonZz/DevOps_Deploy.git
    targetRevision: main
    path: kubernetes/argocd/applications/logging   # 👈 子 Application YAML 所在目錄
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd                      # 子 Application 會建在 argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectResourceOrder=true
      - WaitForChildren=true
