name: CD - Install ArgoCD on K3s

on:
  workflow_dispatch:  # 手動觸發

jobs:
  setup-argocd:
    runs-on: Linux

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Create ArgoCD namespace
        run: kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

      - name: Install ArgoCD
        run: |
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl rollout status deploy/argocd-server -n argocd --timeout=300s

      - name: Apply ArgoCD Application
        run: |
          kubectl apply -f kubernetes/argocd/applications/ -n argocd

      - name: Install ArgoCD CLI
        run: |
           sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
           sudo chmod +x /usr/local/bin/argocd
